import { test } from "node:test";
import assert from "node:assert/strict";
import { createClip, createEditSequence, createTrack, DEFAULT_TRANSFORM } from "../src/sequence/types";
import type { ProjectDocument } from "../src/sequence/types";
import { evaluateClipTransform, clipVolumeAt, ProjectHistory, remapAnimationCharacters } from "../src/sequence/engine";
import { patchClips, rollCut, slipClips, crossfadeAudio } from "../src/sequence/advancedEditing";
import { editPropertiesAt, volumeCurveSamples, gainToDb, dbToGain } from "../src/sequence/properties";
import { assetRange, sourcePreviewProject } from "../src/sequence/sourcePreview";
import { isProjectDocument } from "../src/sequence/validation";
import { emptyAnimation, targetId } from "../src/animation/types";
import { evaluateAt, insertSource, editSource, moveSourcePriority } from "../src/animation/engine";
import { exportAnimation } from "../src/animation/exporters";
import { audioGainAt, resolveAudioSchedule } from "../src/sequence/audio";
import { getSceneLipAt } from "../src/sequence/sceneAudio";
import { sliceExportAudio } from "../src/utils/exportRange";
const key = (time: number, value: number) => ({ id: crypto.randomUUID(), time, value, interpolation: "linear" as const });
function fixture(): ProjectDocument { const root = createEditSequence(); root.id = "root"; root.tracks = [createTrack(0), createTrack(1)]; return { version: 3, id: "p", name: "test", assets: { image: { id: "image", kind: "image", name: "图片", uri: "image.png" }, audio: { id: "audio", kind: "audio", name: "音频", uri: "voice.wav", duration: 10, lipSync: Array(1200).fill(0.5), lipSyncSampleRate: 120 } }, sequences: { root }, rootSequenceId: "root", width: 1920, height: 1080, fps: 30, seed: 1, savedAt: "" }; }
const image = (id: string, start = 0, duration = 2) => createClip({ id, kind: "image", assetId: "image", name: id, start, duration });
test("independent property curves retain legacy animation and use source time", () => { const clip = image("a"); clip.transformKeys = [{ ...DEFAULT_TRANSFORM, id: "old", time: 1, x: 3, y: 20 }]; clip.propertyCurves = { x: { enabled: true, keys: [key(0, 0), key(2, 100)] }, opacity: { enabled: false, keys: [key(0, 0)] } }; assert.equal(evaluateClipTransform(clip, 1).x, 50); assert.equal(evaluateClipTransform(clip, 1).y, 20); assert.equal(evaluateClipTransform(clip, 1).opacity, 1); assert.equal(evaluateClipTransform(clip, 10).x, 100); const patched = { ...clip, ...editPropertiesAt(clip, 1, { x: 60, y: 30 }) }; assert.equal(patched.propertyCurves!.y!.keys[0].value, 30); assert.equal(evaluateClipTransform(patched, 1).x, 60); assert.equal(evaluateClipTransform(clip, 1).x, 50); });
test("property curve hold, inverse hold, bezier, and volume dB are evaluated consistently", () => { const clip = image("a"); const a = key(0, 0), b = key(2, 1); clip.propertyCurves = { volume: { enabled: true, keys: [{ ...a, interpolation: "hold" }, b] } }; assert.equal(clipVolumeAt(clip, 1), 0); clip.propertyCurves.volume!.keys[0].interpolation = "inverse-hold"; assert.equal(clipVolumeAt(clip, 1), 1); clip.propertyCurves.volume!.keys[0] = { ...a, interpolation: "bezier", outHandle: { time: 0.5, value: 0 } }; clip.propertyCurves.volume!.keys[1] = { ...b, inHandle: { time: 1.5, value: 1 } }; assert.ok(Math.abs(clipVolumeAt(clip, 1) - 0.5) < 1e-6); assert.ok(volumeCurveSamples(clip).length < 2048); assert.ok(Math.abs(dbToGain(gainToDb(0.25)) - 0.25) < 1e-9); assert.equal(dbToGain(-60), 0); });
test("batch property changes preserve each clip's other values and reject locked tracks atomically", () => { const p = fixture(); p.sequences.root.tracks[0].clips = [image("a")]; p.sequences.root.tracks[1].clips = [image("b")]; p.sequences.root.tracks[1].clips[0].transform.y = 30; const result = patchClips(p, "root", ["a", "b"], clip => editPropertiesAt(clip, 0, { x: 50 })); assert.equal(result.sequences.root.tracks[1].clips[0].transform.y, 30); assert.equal(result.sequences.root.tracks[0].clips[0].transform.x, 50); p.sequences.root.tracks[1].locked = true; assert.throws(() => patchClips(p, "root", ["a", "b"], () => ({ volume: 2 })), /锁定/); assert.equal(p.sequences.root.tracks[0].clips[0].volume, 1); });
test("slip clamps common source delta while outer clip positions and curves remain intact", () => { const p = fixture(); const a = createClip({ id: "a", kind: "audio", assetId: "audio", name: "a", start: 3, duration: 2, sourceIn: 1, rate: 2 }); p.sequences.root.tracks[0].clips = [a]; const result = slipClips(p, "root", ["a"], 20).sequences.root.tracks[0].clips[0]; assert.equal(result.start, 3); assert.equal(result.duration, 2); assert.equal(result.sourceIn, 6); const zero = slipClips(p, "root", ["a"], -20).sequences.root.tracks[0].clips[0]; assert.equal(zero.sourceIn, 0); });
test("rolling trims preserve outer interval and right source phase, respect source capacity and history", () => { const p = fixture(); p.sequences.root.tracks[0].clips = [image("a", 0, 3), { ...image("b", 3, 2), sourceIn: 2, rate: 2 }]; const history = new ProjectHistory(p); const changed = history.execute(project => rollCut(project, "root", "a", 0.5)); const [a, b] = changed.sequences.root.tracks[0].clips; assert.equal(a.duration, 3.5); assert.equal(b.start, 3.5); assert.equal(b.sourceIn, 3); assert.equal(b.start + b.duration, 5); assert.deepEqual(history.undo(), p); assert.deepEqual(history.redo(), changed); assert.throws(() => rollCut(p, "root", "b", 1), /相邻/); });
test("source preview and ranges use disposable sequences with isolated model identities", () => { const p = fixture(); p.assets.model = { id: "model", kind: "live2d", name: "角色", uri: "model3.json", duration: 5, metadata: { sourceIn: 1, sourceOut: 4 } }; const before = JSON.stringify(p); assert.deepEqual(assetRange(p, p.assets.model), { sourceIn: 1, sourceOut: 4, duration: 3 }); const preview = sourcePreviewProject(p, p.assets.model); assert.equal(preview.project.sequences[preview.sequenceId].kind, "live2d"); assert.equal(JSON.stringify(p), before); assert.notEqual(preview.sequenceId, p.rootSequenceId); });
test("material masks and priority changes restore underlying curves without discarding originals", () => { const doc = emptyAnimation(); const target = targetId("actor", "part", "x"); doc.tracks = [{ definition: { target, characterId: "actor", partId: "part", parameterId: "x", name: "x", group: "g", kind: "parameter", min: 0, max: 100, defaultValue: 0 }, baseValue: 0, animated: false, keys: [] }]; let result = insertSource(doc, { id: "low", kind: "motion", name: "低", start: 0, duration: 2, sourceDuration: 2, offset: 0, speed: 1, curves: { [target]: [key(0, 10), key(2, 10)] } }); result = insertSource(result, { id: "high", kind: "expression", name: "高", start: 0, duration: 2, sourceDuration: 2, offset: 0, speed: 1, curves: { [target]: [key(0, 20), key(2, 20)] } }); assert.equal(evaluateAt(result, 1)[target], 20); assert.equal(evaluateAt(editSource(result, "high", { enabled: false }), 1)[target], 10); assert.equal(evaluateAt(editSource(result, "high", { targetMask: [] }), 1)[target], 10); assert.equal(evaluateAt(moveSourcePriority(result, "low", 1), 1)[target], 10); assert.equal(result.groups[1].curves[target][0].value, 20); const remapped = remapAnimationCharacters(editSource(result, "high", { targetMask: [target] }), { actor: "new" }); assert.deepEqual(remapped.groups[1].targetMask, [targetId("new", "part", "x")]); });
test("pose presets export selected parameters as exp3 and never serialize a motion as expression", () => { const doc = emptyAnimation(); doc.tracks = ["x", "y"].map(parameterId => ({ definition: { target: targetId("actor", "p", parameterId), characterId: "actor", partId: "p", parameterId, name: parameterId, group: "g", kind: "parameter" as const, min: 0, max: 100, defaultValue: 0 }, baseValue: 10, animated: false, keys: [] })); const result = exportAnimation(doc, { kind: "expression", name: "pose", characterId: "actor", partId: "p", start: 0, end: 1, time: 0, fps: 30, fadeIn: 0.2, scope: "all", destination: "library", targets: [doc.tracks[0].definition.target] }, 3); assert.equal(result.extension, "exp3.json"); const file = JSON.parse(result.text); assert.equal(file.Parameters.length, 1); assert.equal(file.Parameters[0].Id, "x"); assert.equal(file.Parameters[0].Blend, "Overwrite"); });
test("audio envelopes use independent volume curves and carry pitch and mouth offsets", () => { const p = fixture(); const audio = createClip({ id: "a", kind: "audio", assetId: "audio", name: "a", start: 0, duration: 3, preservePitch: false, lipSyncActorId: "actor", lipSyncOffset: 1, propertyCurves: { volume: { enabled: true, keys: [key(0, 0.5), key(3, 1)] } } }); p.sequences.root.tracks[0].clips = [audio]; const schedule = resolveAudioSchedule(p); assert.equal(schedule[0].preservePitch, false); assert.ok(Math.abs(audioGainAt(schedule[0], 1.5) - 0.75) < 1e-6); assert.equal(getSceneLipAt(p)("root", "actor", 0.5, ["root"]), 0); assert.ok(getSceneLipAt(p)("root", "actor", 1.5, ["root"]) > 0); });
test("range export clips and rebases audio while retaining fade and source curve phases", () => { const track = { id: "a", start: 1, duration: 6, sourceIn: 2, playbackRate: 2, gain: 1, fadeIn: 2, fadeOut: 2, gainEnvelopes: [{ gain: 1, keys: [{ time: 0, value: 0 }, { time: 6, value: 1 }], fadeInStart: 0, fadeInDuration: 2, fadeOutStart: 4, fadeOutDuration: 2 }] }; const result = sliceExportAudio([track], 3, 5)[0]; assert.equal(result.start, 0); assert.equal(result.duration, 2); assert.equal(result.sourceIn, 6); assert.equal(result.gainEnvelopes![0].fadeInStart, -2); assert.equal(result.gainEnvelopes![0].keys[1].time, 4); assert.equal(sliceExportAudio([track], 8, 10).length, 0); });
test("crossfade applies complementary fades to overlapping audio on separate lanes", () => { const p = fixture(); p.sequences.root.tracks[0].clips = [createClip({ id: "a", kind: "audio", assetId: "audio", name: "a", start: 0, duration: 3 })]; p.sequences.root.tracks[1].clips = [createClip({ id: "b", kind: "audio", assetId: "audio", name: "b", start: 2, duration: 3 })]; const result = crossfadeAudio(p, "root", ["a", "b"], 1); const schedule = resolveAudioSchedule(result); assert.ok(Math.abs(audioGainAt(schedule[0], 2.5) + audioGainAt(schedule[1], 0.5) - 1) < 1e-6); assert.ok(isProjectDocument(result)); });
test("validation rejects invalid independent property curves without breaking old projects", () => { const p = fixture(); p.sequences.root.tracks[0].clips = [image("a")]; assert.ok(isProjectDocument(p)); p.sequences.root.tracks[0].clips[0].propertyCurves = { x: { enabled: true, keys: [key(0, Infinity)] } }; assert.equal(isProjectDocument(p), false); });

test("editing property values moves existing Bezier handles with their key",()=>{
  const clip=image("a");clip.propertyCurves={x:{enabled:true,keys:[{...key(1,20),interpolation:"bezier",inHandle:{time:0.5,value:10},outHandle:{time:1.5,value:30}}]}};
  const changed=editPropertiesAt(clip,1,{x:40}).propertyCurves!.x!.keys[0];
  assert.deepEqual(changed.inHandle,{time:0.5,value:30});assert.deepEqual(changed.outHandle,{time:1.5,value:50});assert.equal(changed.id,clip.propertyCurves.x!.keys[0].id);
});
